version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: 
          name: Unit Testing
          command: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      # build 
      - run: 
          name: Build
          command: npm build

      # Deploy 
      - run: 
          name: Deploy to S3 dev (lol-champ-select)
          command: aws s3 cp ./dist/ChampSelect s3://lol-champ-select --recursive --acl public-read